### ISSUE TITLE
[question] updating the list from here

### ISSUE THREAD

**Issue by dnmTX** [dead-hosts/cameleon_web_sysctl.org#1]
@funilrys  i just saw that you have the Cameleon lists here which is great.I'm actually using it in addition to StevenBlack's one and downloading it from the website(http://sysctl.org/cameleon/) but the thing is that i'm not sure that it's been maintained very well or very often(# Last updated : 2018-03-17).Isn't better if i download it from here(https://github.com/dead-hosts/cameleon_web_sysctl.org/blob/master/clean.list) ,at least it's been filtered cause it looks like whoever maintaining  that lists most likely abandoned it but there are still plenty of active domains so it's usable.If your answer is YES i also need to know how often you perform filtering,this way i can do cron schedule instead of doing it manually every week or so. And last but not least if all that i asked so far is YES and in the future you decide to remove it from your list here,or change destination(URL) i would appreciate some heads up. Thank you for your excellent work,i do appreciate it. 👍

**Comment by dnmTX** [comment]
@funilrys thank you for that very informative and explanatory answer.I'll start downloading that lists from here.Just one more thing about "how often",so you said that every 24 hours or so you do filtering,and now that we talking about removing(dead) domains and not adding new ones(which is more critical) i thing it's safe to schedule(on my end) to download it either once every week or twice per month(like every 1st and 14th of the month).What do you think?

**Comment by funilrys** [comment]
@dnmTX as we use Travis CI, it's cheap to run every 24 hours but yes if there no new addition in one month we can increase the following to more days in the future. 
But to be fear, it'll be for my next part of the work which will start after the first release of PyFunceble (it's actually in beta). Indeed I'm talking about a deep analytic of every repository to improve performance and not give too much stress to Travis CI infrastructure.

https://github.com/dead-hosts/cameleon_web_sysctl.org/blob/01d33f4c37eb97f690d1176bc59d0891e94972bd/info.json#L7

**Comment by dnmTX** [comment]
@funilrys  thank you man,you made my day today with me finding this here(filtered cameleon lists) and you making the PR  [https://github.com/StevenBlack/hosts/pull/651](url) .Good luck with the project here,we need that for sure.Oh...and just a heads up,not sure do you know or not but if you don't: ConBlockerLists moved to GitLab so there are new URL's for the lists. Thank you again.

**Comment by funilrys** [comment]
@dnmTX I was informed by https://github.com/dead-hosts/CoinBlockersLists_git_ZeroDot1/issues/1but 

Thanks :+1:

**Comment by dnmTX** [comment]
@funilrys  sorry but to clarify something(i think you misunderstood one of my questions).When i was asking to give me heads up if you change URL or destination i didn't mean the upstream URL but THIS:
https://raw.githubusercontent.com/dead-hosts/cameleon_web_sysctl.org/master/clean.list one,which is the one i'm going to be using to download the lists from now on and it's very important to stay the same due to i'll schedule my script to run in certain days in the background so even if let's say you change the URL or something i wouldn't even know.That is what i was asking cause such a things are important for things to work ON MY END(with very little supervision if possible).

**Comment by funilrys** [comment]
@dnmTX I did not answer that because when writing the system I applied some standards.

One of those standards is that `clean.list` will never be renamed! And that's True for every repository!!

So if it does not exist that will probably mean that there is no ACTIVE but even in that case we append an empty string to `clean.list` 🙂
